### ISSUE TITLE
unable to use

### ISSUE THREAD

**Issue by ajayashuba** [quasarframework/app-extension-icon-factory#19]
can you show me how to use this as cli  https://github.com/quasarframework/quasar-icon-factory, i used like this  ```node cli.js -p svg spa -s /root/quasar/src/statics/logo.png -t  ./ ```  it gives me error  ```TypeError: iconfactory.svg is not a function
    at Object.<anonymous> (/root/quasar-icon-factory/bin/cli.js:103:21)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)```

**Comment by nothingismagick** [comment]
Thanks for the reminder. As soon as we ship Quasar 1.0 beta I will investigate this and a few other issues and release this project as an official app extension.

**Comment by RohanTalip** [comment]
Actually, I have been able to get around these errors by checking out the repository at the last commit on May 28, 2018, i.e. before commit 6a6fca55d0d1da7b3edd9117e4454608725b05c6 ("Webpack integration preview.").

**Comment by nothingismagick** [comment]
This module is about to undergo a massive rebuild to be inline with quasar-app-extensions. It probably won't even hook into webpack for performance reasons.

**Comment by nothingismagick** [comment]
I have rebuilt the exports from the index.js file so that the CLI is now working again, as intended.
