### ISSUE TITLE
Compile errors on windows when using `import { icon-factory }`

### ISSUE THREAD

**Issue by webnoob** [quasarframework/app-extension-icon-factory#37]
I've got VS installed but still had to run ` npm install --global --production windows-build-tools` in order for it to compile.

I forget the exact error but it was complaining about not having access to MSBuild.exe (which I do).

**Comment by nothingismagick** [comment]
Does this still happen to you?

**Comment by webnoob** [comment]
I can get sharp to compile but no matter what I did (on windows) I couldn't get sharp to import with an error (generally a node version mismatch error or this:

```
PATH\node_modules\sharp\build\Release\sharp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (PATH\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (PATH\node_modules\sharp\lib\constructor.js:10:34)
```

My "fix" was to dual boot to linux and do it on there ...

**Comment by nothingismagick** [comment]
This is an edge case not related to the core features of the library. Closing
